CREATE USER cip20         WITH PASSWORD '${POSTGRES_CIP_PASS}';

CREATE USER cip20_user    WITH PASSWORD '${POSTGRES_USR_PASS}';
GRANT cip20_user TO cip20;

CREATE USER cip20_upload  WITH PASSWORD '${POSTGRES_UPL_PASS}';
GRANT cip20_upload TO cip20;

CREATE USER cip20_pgrest  WITH PASSWORD '${POSTGREST_PASS}';
GRANT cip20_pgrest TO cip20;
