FROM nginx

LABEL maintainer="Paul Dziemiela <Paul.Dziemiela@erg.com>"

COPY ./nginx/html       /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
    
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
