import os,sys,arcpy;

aliashash = {
    'addressdate'                   :'AddressDate'
   ,'address'                       :'Address'
   ,'addresstype'                   :'AddressType'
   ,'agency_type_code'              :'Agency Type Code'
   ,'aiannhns'                      :'American Indian/Alaska Native/Native Hawaiian Area Census Code'
   ,'aiannhr'                       :'AIANNH Recognition Code'
   ,'aland'                         :'Land Area'
   ,'angle_direction'               :'Angle Direction'
   ,'angle_rounded'                 :'Angle Rounded'
   ,'aquifername'                   :'AquiferName'
   ,'aquifertypename'               :'AquiferTypeName'
   ,'arbolatesu'                    :'UpstreamCumulativeStreamKm'
   ,'areaacres'                     :'AreaAcres'
   ,'areasqkm'                      :'AreaSqKm'
   ,'areasqkm_geo'                  :'AreaSqKm (Geodetic)'
   ,'arqnavma'                      :'AddRemoveFlowNotAvailableMA'
   ,'attributeaccuracyreport'       :'AttributeAccuracyReport'
   ,'avgqadjma'                     :'GageFlowFlowlineBottomMA'
   ,'awater'                        :'Water Area'
   ,'beginningdate'                 :'BeginningDate'
   ,'burn'                          :'Burn'
   ,'calendardate'                  :'CalendarDate'
   ,'cat_hr_count'                  :'HR Catchment Count'
   ,'cat_joinkey'                   :'Catchment JoinKey'
   ,'cat_mr_count'                  :'MR Catchment Count'
   ,'catchment'                     :'Catchment'
   ,'catchmentareasqkm'             :'CatchmentAreaSqKm'
   ,'catchmentresolution'           :'CatchmentResolution'
   ,'catchmentstatecode'            :'CatchmentStateCode'
   ,'cip_action'                    :'CIP Action'
   ,'cip_date'                      :'CIP Date'
   ,'cip_joinkey'                   :'CIP JoinKey'
   ,'cip_method'                    :'CIP Method'
   ,'cip_parms'                     :'CIP Parameters'
   ,'cip_version'                   :'CIP Version'
   ,'city'                          :'City'
   ,'city_name'                     :'City Name'
   ,'class'                         :'Class'
   ,'classfp'                       :'ClassFP Code'
   ,'classmod'                      :'ClassMod'
   ,'completenessreport'            :'CompletenessReport'
   ,'comptyp'                       :'Component Type'
   ,'constructiondatetext'          :'ConstructionDateText'
   ,'contactemailaddress'           :'ContactEmailAddress'
   ,'contactinstructions'           :'ContactInstructions'
   ,'contactorganization'           :'ContactOrganization'
   ,'contactvoicetelephone'         :'ContactVoiceTelephone'
   ,'contributingdrainageareameasun':'ContributingDrainageAreaMeasUnit'
   ,'contributingdrainageareameasva':'ContributingDrainageAreaMeasValue'
   ,'country_name'                  :'Country Name'
   ,'countrycode'                   :'CountryCode'
   ,'county_name'                   :'County Name'
   ,'countycode'                    :'CountyCode'
   ,'dasqmi'                        :'DrainageAreaSqMi'
   ,'datasetcredit'                 :'DatasetCredit'
   ,'deltalevel'                    :'DeltaLevel'
   ,'direction'                     :'Direction'
   ,'divdasqkm'                     :'DivergenceRoutedDrainAreaSqKm'
   ,'divergence'                    :'DivergenceCode'
   ,'dndraincou'                    :'DownstreamDrainageCount'
   ,'dnhydroseq'                    :'DownstreamMainPathHydroSeq'
   ,'dnlevel'                       :'DownstreamMainPathStreamLevel'
   ,'dnlevelpat'                    :'DownstreamMainPathLevelPathID'
   ,'dnminorhyd'                    :'DownstreamMinorHydroSequence'
   ,'drainageareameasure_measureunt':'DrainageAreaMeasure MeasureUnit'
   ,'drainageareameasure_measureval':'DrainageAreaMeasure MeasureValue'
   ,'elevation'                     :'Elevation'
   ,'elevfixed'                     :'IsElevationFixed'
   ,'end_date'                      :'End Date'
   ,'endingdate'                    :'EndingDate'
   ,'event_areasqkm'                :'Event AreaSqKm'
   ,'event_lengthkm'                :'Event LengthKm'
   ,'eventdate'                     :'EventDate'
   ,'eventoffset'                   :'EventOffset'
   ,'eventtype'                     :'EventType'
   ,'external_permit_nmbr'          :'External Permit Number'
   ,'fcode'                         :'FCode'
   ,'fdate'                         :'FDate'
   ,'feature_permanent_identifier'  :'Feature Permanent Identifier'
   ,'featureclassref'               :'FeatureClassReference'
   ,'featuredetailurl'              :'FeatureDetailURL'
   ,'featureid'                     :'FeatureID'
   ,'featuretype'                   :'FeatureType'
   ,'fips_code'                     :'FIPS Code'
   ,'flowdir'                       :'FlowDir'
   ,'fmeasure'                      :'FromMeasure'
   ,'formationtypetext'             :'FormationTypeText'
   ,'fromhydroseq'                  :'FromHydrologicSequence'
   ,'frommeas'                      :'FromMeasure'
   ,'fromnhdpid'                    :'FromNHDPlusID'
   ,'fromnode'                      :'FromNode'
   ,'frompermid'                    :'FromPermanentIdentifier'
   ,'fromvpuid'                     :'FromVPUID'
   ,'ftype'                         :'FType'
   ,'funcstat'                      :'Functional Status'
   ,'gageadjma'                     :'IsGageAdjustedMA'
   ,'gageidma'                      :'NWISGageIDMA'
   ,'gageqma'                       :'GageFlowMA'
   ,'gapdistkm'                     :'GapDistanceKm'
   ,'geogstate'                     :'Geographic State Code'
   ,'geoid'                         :'Geographic Identifier'
   ,'gnis_id'                       :'GNIS_ID'
   ,'gnis_name'                     :'GNIS_Name'
   ,'gridcode'                      :'GridCode'
   ,'h3hexagonaddr'                 :'H3 Hexagon Addr'
   ,'hasgeo'                        :'HasGeo'
   ,'hasvaa'                        :'HasVAA'
   ,'horizontalaccuracymeasureunit' :'HorizontalAccuracyMeasureUnit'
   ,'horizontalaccuracymeasureval'  :'HorizontalAccuracyMeasureValue'
   ,'horizontalcollectionmethodname':'HorizontalCollectionMethodName'
   ,'horizontalcoordinatereferences':'HorizontalCoordinateReferences'
   ,'horizpositionalaccuracyreport' :'HorizontalPositionalAccuracyReport'
   ,'hu'                            :'HU'
   ,'huc12'                         :'HUC12'
   ,'huceightdigitcode'             :'Eight-digit HUC Code'
   ,'humod'                         :'HUMod'
   ,'hutype'                        :'HUType'
   ,'hwnodesqkm'                    :'HeadwaterNodeDrainageAreaSqKm'
   ,'hwtype'                        :'HeadwaterType'
   ,'hydroaddressid'                :'HydroAddressID'
   ,'hydroseq'                      :'HydrologicSequence'
   ,'innetwork'                     :'InNetwork'
   ,'intptlat'                      :'Internal Point Latitude'
   ,'intptlon'                      :'Internal Point Longitude'
   ,'isalaskan'                     :'IsAlaskan'
   ,'iscoastal'                     :'IsCoastal'
   ,'isheadwater'                   :'IsHeadwater'
   ,'isnavigable'                   :'IsNavigable'
   ,'isocean'                       :'IsOcean'
   ,'issink'                        :'IsSink'
   ,'issue_date'                    :'Issue Date'
   ,'issuing_agency'                :'Issuing Agency'
   ,'istribal'                      :'IsTribal'
   ,'istribal_areasqkm'             :'IsTribal AreaSqKm'
   ,'keyword'                       :'Keyword'
   ,'latitudemeasure'               :'LatitudeMeasure'
   ,'latsite'                       :'LatitudeSite'
   ,'lengthkm'                      :'LengthKm'
   ,'levelpathi'                    :'LevelPathIdentifier'
   ,'load_date'                     :'Load Date'
   ,'load_id'                       :'Load Identifier'
   ,'loaddate'                      :'LoadDate'
   ,'localaqfrname'                 :'LocalAquiferName'
   ,'logicalconsistencyreport'      :'LogicalConsistencyReport'
   ,'longitudemeasure'              :'LongitudeMeasure'
   ,'lonsite'                       :'LongitudeSite'
   ,'mainpath'                      :'MainPath'
   ,'maxelevraw'                    :'MaximumElevationRaw'
   ,'maxelevsmo'                    :'MaximumElevationSmoothed'
   ,'measure'                       :'Measure'
   ,'meta_processid'                :'Meta ProcessIdentifier'
   ,'metadatadate'                  :'MetadataDate'
   ,'metadatastandardname'          :'MetadataStandardName'
   ,'metadatastandardversion'       :'MetadataStandardVersion'
   ,'metasourceid'                  :'MetaSourceID'
   ,'minelevraw'                    :'MinimumElevationRaw'
   ,'minelevsmo'                    :'MinimumElevationSmoothed'
   ,'monitoringlocationdescription' :'MonitoringLocationDescription'
   ,'monitoringlocationidentifier'  :'MonitoringLocationIdentifier'
   ,'monitoringlocationname'        :'MonitoringLocationName'
   ,'monitoringlocationtypename'    :'MonitoringLocationTypeName'
   ,'mtfcc'                         :'MAF/TIGER Feature Class Code'
   ,'name'                          :'Name'
   ,'namelsad'                      :'Name LSAD'
   ,'nhdplusid'                     :'NHDPlusID'
   ,'nodenumber'                    :'NodeNumber'
   ,'noncontributingareaacres'      :'NonContributingAreaAcres'
   ,'noncontributingareasqkm'       :'NonContributingAreaSqKm'
   ,'onnetwork'                     :'OnNetwork'
   ,'onoffnet'                      :'OnNetwork'
   ,'organizationformalname'        :'OrganizationFormalName'
   ,'organizationidentifier'        :'OrganizationIdentifier'
   ,'original_issue_date'           :'Original Issue Date'
   ,'originator'                    :'Originator'
   ,'overlap_measure'               :'Overlap Measure'
   ,'pathlength'                    :'PathLength'
   ,'pathtimema'                    :'PathTimeMeanAverage'
   ,'permanent_identifier'          :'Permanent_Identifier'
   ,'permid_joinkey'                :'PermID JoinKey'
   ,'permit_name'                   :'Permit Name'
   ,'permit_status_code'            :'Permit Status Code'
   ,'permit_type_code'              :'Permit Type Code'
   ,'petma'                         :'CatchmentPotentialETMA'
   ,'pgm_sys_id'                    :'Program System ID'
   ,'pgm_sys_acrm'                  :'Program System Acronym'
   ,'postal_code'                   :'Postal Code'
   ,'postalcode'                    :'PostalCode'
   ,'primary_name'                  :'Primary Name'
   ,'processdate'                   :'ProcessDate'
   ,'processdescription'            :'ProcessDescription'
   ,'providername'                  :'ProviderName'
   ,'publicationdate'               :'PublicationDate'
   ,'purpcode'                      :'PurposeCode'
   ,'qama'                          :'FlowEstARunoffMA'
   ,'qbma'                          :'FlowEstBExcessETMA'
   ,'qcma'                          :'FlowEstCRefGageRegressMA'
   ,'qdma'                          :'FlowEstDAdditionRemovalMA'
   ,'qema'                          :'FlowEstEGageAdjustedMA'
   ,'qfma'                          :'FlowEstFGageSequesterMA'
   ,'qgadjma'                       :'GageFlowAdjustmentMA'
   ,'qgnavma'                       :'GageAdjustmentNotAvailableMA'
   ,'qincrama'                      :'IncrFlowEstARunoffMA'
   ,'qincrbma'                      :'IncrFlowEstBExcessETMA'
   ,'qincrcma'                      :'IncrFlowEstCRefGageRegressMA'
   ,'qincrdma'                      :'IncrFlowEstDAdditionRemovalMA'
   ,'qincrema'                      :'IncrFlowEstEGageAdjustedMA'
   ,'qincrfma'                      :'IncrFlowEstFGageSequesterMA'
   ,'qlossma'                       :'FlowLossFromPotentialETMA'
   ,'rad_hr_area_count'             :'RAD HR Area Count'
   ,'rad_hr_event_count'            :'RAD HR Event Count'
   ,'rad_hr_line_count'             :'RAD HR Line Count'
   ,'rad_hr_point_count'            :'RAD HR Point Count'
   ,'rad_mr_area_count'             :'RAD MR Area Count'
   ,'rad_mr_event_count'            :'RAD MR Event Count'
   ,'rad_mr_line_count'             :'RAD MR Line Count'
   ,'rad_mr_point_count'            :'RAD MR Point Count'
   ,'reachcode'                     :'ReachCode'
   ,'reachresolution'               :'ReachResolution'
   ,'reachsmdate'                   :'ReachSMDate'
   ,'referencegage'                 :'ReferenceGage'
   ,'referencegnis_ids'             :'ReferenceGNIS_IDs'
   ,'registry_id'                   :'Registry ID'
   ,'resolution'                    :'Resolution'
   ,'retirement_date'               :'Retirement Date'
   ,'rpuid'                         :'RPUID'
   ,'rtndiv'                        :'HasReturningDivergence'
   ,'sfiddetailurl'                 :'SFIDDetailURL'
   ,'slope'                         :'Slope'
   ,'slopelenkm'                    :'SlopeLengthKm'
   ,'source_datadesc'               :'Source Data Description'
   ,'source_datasetid'              :'Source DatasetID'
   ,'source_featureid'              :'Source FeatureID'
   ,'source_featureid2'             :'Source FeatureID2'
   ,'source_joinkey'                :'Source JoinKey'
   ,'source_originator'             :'Source Originator'
   ,'source_series'                 :'Source Series'
   ,'source_subdivision'            :'Source Subdivision'
   ,'sourceagency'                  :'SourceAgency'
   ,'sourcecitationabbreviation'    :'SourceCitationAbbreviation'
   ,'sourcecontribution'            :'SourceContribution'
   ,'sourcecurrentnessreference'    :'SourceCurrentnessReference'
   ,'sourcedatadesc'                :'SourceDataDesc'
   ,'sourcedataset'                 :'SourceDataset'
   ,'sourcefc'                      :'SourceFeatureClass'
   ,'sourcefeatureid'               :'SourceFeatureID'
   ,'sourcefeatureurl'              :'SourceFeatureURL'
   ,'sourceid'                      :'SourceID'
   ,'sourcemapscalenumeric'         :'SourceMapScaleNumeric'
   ,'sourceoriginator'              :'SourceOriginator'
   ,'sourcescaledenominator'        :'SourceScaleDenominator'
   ,'src2cip_joinkey'               :'Src2CIP JoinKey'
   ,'src_area_count'                :'Source Area Count'
   ,'src_event_count'               :'Source Event Count'
   ,'src_line_count'                :'Source Line Count'
   ,'src_point_count'               :'Source Point Count'
   ,'start_date'                    :'StartDate'
   ,'startflag'                     :'IsHeadwater'
   ,'state'                         :'State'
   ,'state_cd'                      :'StateCode'
   ,'state_code'                    :'State Code'
   ,'state_name'                    :'State Name'
   ,'state_count'                   :'State Count'
   ,'statecode'                     :'StateCode'
   ,'statens'                       :'ANSI Feature Code'
   ,'stusps'                        :'USPS State Abbreviation'
   ,'stateorprovince'               :'StateOrProvince'
   ,'states'                        :'States'
   ,'station_nm'                    :'StationName'
   ,'statusflag'                    :'StatusFlag'
   ,'streamcalc'                    :'StreamCalculator'
   ,'streamleve'                    :'StreamLevel'
   ,'streamorde'                    :'StreamOrder'
   ,'terminalfl'                    :'IsNetworkEnd'
   ,'terminalpa'                    :'TerminalPathIdentifier'
   ,'termination_date'              :'Termination Date'
   ,'thinner'                       :'Thinner'
   ,'title'                         :'Title'
   ,'tmeasure'                      :'ToMeasure'
   ,'tnmid'                         :'The National Map ID'
   ,'tohuc'                         :'ToHUC'
   ,'tohydroseq'                    :'ToHydrologicSequence'
   ,'tomeas'                        :'ToMeasure'
   ,'tonhdpid'                      :'ToNHDPlusID'
   ,'tonode'                        :'ToNode'
   ,'topermid'                      :'ToPermanentIdentifier'
   ,'totdasqkm'                     :'TotalDrainageAreaSqKm'
   ,'totma'                         :'TimeOfTravelMeanAverage'
   ,'tovpuid'                       :'ToVPUID'
   ,'tribal_land_code'              :'Tribal Land Code'
   ,'tribal_land_name'              :'Tribal Land Name'
   ,'typeofsourcemedia'             :'TypeOfSourceMedia'
   ,'uphydroseq'                    :'UpstreamMainPathHydroSeq'
   ,'uplevelpat'                    :'UpstreamMainPathLevelPathID'
   ,'us_mexico_border_ind'          :'US/Mexico Border Indicator'
   ,'value_date'                    :'Date Value'
   ,'value_num'                     :'Numeric Value'
   ,'value_str'                     :'String Value'
   ,'vama'                          :'VelocityARunoffMA'
   ,'vbma'                          :'VelocityBExcessETMA'
   ,'vcma'                          :'VelocityCRefGageRegressMA'
   ,'vdma'                          :'VelocityDAdditionRemovalMA'
   ,'vema'                          :'VelocityEGageAdjustedMA'
   ,'verticalaccuracymeasureunit'   :'VerticalAccuracyMeasureUnit'
   ,'verticalaccuracymeasurevalue'  :'VerticalAccuracyMeasureValue'
   ,'verticalcollectionmethodname'  :'VerticalCollectionMethodName'
   ,'verticalcoordinatereferencesys':'VerticalCoordinateReferenceSystem'
   ,'verticalmeasure_measureunit'   :'VerticalMeasure MeasureUnit'
   ,'verticalmeasure_measurevalue'  :'VerticalMeasure MeasureValue'
   ,'vertpositionalaccuracyreport'  :'VerticalPositionalAccuracyReport'
   ,'visibilityfilter'              :'VisibilityFilter'
   ,'vpuid'                         :'VPUID'
   ,'vpuin'                         :'VPUIn'
   ,'vpuout'                        :'VPUOut'
   ,'wbarea_permanent_identifier'   :'WBArea_Permanent_Identifier'
   ,'welldepthmeasure_measureunit'  :'WellDepthMeasure MeasureUnit'
   ,'welldepthmeasure_measurevalue' :'WellDepthMeasure MeasureValue'
   ,'wellholedepthmeasure_measureun':'WellHoleDepthMeasure MeasureUnit'
   ,'wellholedepthmeasure_measureva':'WellHoleDepthMeasure MeasureValue'
   ,'xwalk_catresolution'           :'XWalk Catchment Resolution'
   ,'xwalk_huc12'                   :'XWalk HUC12'
   ,'xwalk_huc12_areasqkm'          :'XWalk HUC12 AreaSqKm'
   ,'xwalk_huc12_mr_count'          :'XWalk HUC12 MR Count'
   ,'xwalk_huc12_version'           :'XWalk HUC12 Version'
   ,'xwalk_method'                  :'XWalk Method'
};

def update_aliases(
    target_ws
   ,table_name
):
   fields = arcpy.ListFields(target_ws + os.sep + table_name);
   
   for fld in fields:
      
      if fld.name in aliashash:
         
         if fld.aliasName != aliashash[fld.name]:
         
            arcpy.AlterField_management(
                in_table        = target_ws + os.sep + table_name
               ,field           = fld.name
               ,new_field_alias = 'DZ'
            );
            arcpy.AlterField_management(
                in_table        = target_ws + os.sep + table_name
               ,field           = fld.name
               ,new_field_alias = aliashash[fld.name]
            );
      